/*
 * AdminUI.java
 *
 * Created on __DATE__, __TIME__
 */

package view;

import view.ModifySelectUI;

/**
 *
 * @author  __USER__
 */
public class AdminUI extends javax.swing.JFrame {

	/**
	 * 
	 */
	private static final long serialVersionUID = 3098318020969452566L;
	/** Creates new form AdminUI */
	public AdminUI() {
		initComponents();
		setLocationRelativeTo(null);
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jButton1 = new javax.swing.JButton();
		jButton2 = new javax.swing.JButton();
		jButton3 = new javax.swing.JButton();
		jButton4 = new javax.swing.JButton();
		jButton5 = new javax.swing.JButton();
		jLabel3 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		jLabel5 = new javax.swing.JLabel();
		jLabel6 = new javax.swing.JLabel();
		jLabel7 = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jPanel1.setBackground(new java.awt.Color(255, 255, 255));

		jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/img/bigui.png"))); // NOI18N

		jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/img/logo.png"))); // NOI18N

		jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/img/addlogo.png"))); // NOI18N
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/img/deletelogo.png"))); // NOI18N
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton2ActionPerformed(evt);
			}
		});

		jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/img/searchlogo.png"))); // NOI18N
		jButton3.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton3ActionPerformed(evt);
			}
		});

		jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/img/modifylogo.png"))); // NOI18N
		jButton4.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton4ActionPerformed(evt);
			}
		});

		jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/img/exitlogo.png"))); // NOI18N
		jButton5.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton5ActionPerformed(evt);
			}
		});

		jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/img/pluslogo.png"))); // NOI18N

		jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/img/deletelogo1.png"))); // NOI18N

		jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/img/searchlogo1.png"))); // NOI18N

		jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/img/modifylogo1.png"))); // NOI18N

		jLabel7.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 20));
		jLabel7.setText("\u7ba1\u7406\u754c\u9762");

		org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(
				jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout
				.setHorizontalGroup(jPanel1Layout
						.createParallelGroup(
								org.jdesktop.layout.GroupLayout.LEADING)
						.add(jPanel1Layout
								.createSequentialGroup()
								.add(1, 1, 1)
								.add(jLabel1,
										org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
										446,
										org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
								.add(18, 18, 18)
								.add(jPanel1Layout
										.createParallelGroup(
												org.jdesktop.layout.GroupLayout.LEADING)
										.add(jPanel1Layout
												.createSequentialGroup()
												.addPreferredGap(
														org.jdesktop.layout.LayoutStyle.RELATED)
												.add(jLabel2)
												.addPreferredGap(
														org.jdesktop.layout.LayoutStyle.RELATED)
												.add(jLabel7))
										.add(jPanel1Layout
												.createSequentialGroup()
												.add(162, 162, 162)
												.add(jPanel1Layout
														.createParallelGroup(
																org.jdesktop.layout.GroupLayout.TRAILING)
														.add(jLabel3)
														.add(jPanel1Layout
																.createParallelGroup(
																		org.jdesktop.layout.GroupLayout.LEADING)
																.add(jLabel5)
																.add(jLabel4)
																.add(jLabel6)))
												.add(40, 40, 40)
												.add(jPanel1Layout
														.createParallelGroup(
																org.jdesktop.layout.GroupLayout.LEADING)
														.add(jButton4,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																408,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
														.add(jPanel1Layout
																.createSequentialGroup()
																.add(jPanel1Layout
																		.createParallelGroup(
																				org.jdesktop.layout.GroupLayout.TRAILING)
																		.add(org.jdesktop.layout.GroupLayout.LEADING,
																				jButton3,
																				0,
																				0,
																				Short.MAX_VALUE)
																		.add(jButton2,
																				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																				408,
																				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
																		.add(org.jdesktop.layout.GroupLayout.LEADING,
																				jButton1,
																				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																				408,
																				Short.MAX_VALUE))
																.addPreferredGap(
																		org.jdesktop.layout.LayoutStyle.RELATED,
																		org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																		Short.MAX_VALUE)))))
								.add(146, 146, 146)
								.add(jButton5,
										org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
										60,
										org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
								.add(100, 100, 100)));
		jPanel1Layout
				.setVerticalGroup(jPanel1Layout
						.createParallelGroup(
								org.jdesktop.layout.GroupLayout.LEADING)
						.add(jPanel1Layout
								.createSequentialGroup()
								.add(jPanel1Layout
										.createParallelGroup(
												org.jdesktop.layout.GroupLayout.TRAILING,
												false)
										.add(org.jdesktop.layout.GroupLayout.LEADING,
												jPanel1Layout
														.createSequentialGroup()
														.add(jPanel1Layout
																.createParallelGroup(
																		org.jdesktop.layout.GroupLayout.LEADING)
																.add(jPanel1Layout
																		.createSequentialGroup()
																		.add(34,
																				34,
																				34)
																		.add(jButton5,
																				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																				59,
																				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
																.add(jPanel1Layout
																		.createSequentialGroup()
																		.add(49,
																				49,
																				49)
																		.add(jLabel7)))
														.addPreferredGap(
																org.jdesktop.layout.LayoutStyle.RELATED,
																68,
																Short.MAX_VALUE)
														.add(jLabel3))
										.add(org.jdesktop.layout.GroupLayout.LEADING,
												jPanel1Layout
														.createSequentialGroup()
														.add(jLabel2)
														.add(40, 40, 40)
														.add(jButton1,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																67,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
								.add(44, 44, 44)
								.add(jPanel1Layout
										.createParallelGroup(
												org.jdesktop.layout.GroupLayout.TRAILING)
										.add(jButton2,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
												65,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
										.add(jLabel4,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
												76,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
								.add(56, 56, 56)
								.add(jPanel1Layout
										.createParallelGroup(
												org.jdesktop.layout.GroupLayout.LEADING)
										.add(jButton3,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
												64,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
										.add(jLabel5))
								.add(jPanel1Layout
										.createParallelGroup(
												org.jdesktop.layout.GroupLayout.LEADING)
										.add(jPanel1Layout
												.createSequentialGroup()
												.add(60, 60, 60)
												.add(jButton4,
														org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
														63,
														org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
										.add(jPanel1Layout
												.createSequentialGroup()
												.add(68, 68, 68)
												.add(jLabel6,
														org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
														46,
														org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
						.add(jLabel1));

		org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				org.jdesktop.layout.GroupLayout.LEADING).add(jPanel1,
				org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
				org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
		layout.setVerticalGroup(layout.createParallelGroup(
				org.jdesktop.layout.GroupLayout.LEADING).add(jPanel1,
				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
				org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {
		new ModifySelectUI().setVisible(true);
		this.dispose();
	}

	private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {
		new Search().setVisible(true);
		this.dispose();
	}

	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
		new DeleteUI().setVisible(true);
		this.dispose();
	}

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
		new AddUI().setVisible(true);
		this.dispose();
	}

	private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {
		new Admin().setVisible(true);
		this.dispose();
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new AdminUI().setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JButton jButton3;
	private javax.swing.JButton jButton4;
	private javax.swing.JButton jButton5;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JPanel jPanel1;
	// End of variables declaration//GEN-END:variables

}