/*
 * Change.java
 *
 * Created on __DATE__, __TIME__
 */

package view;

/**
 *
 * @author  __USER__
 */
public class Change extends javax.swing.JFrame {

	/**
	 * 
	 */
	private static final long serialVersionUID = -5258653294722418072L;
	/** Creates new form Change */
	public Change() {
		initComponents();
		setLocationRelativeTo(null);
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		jTextField1 = new javax.swing.JTextField();
		jButton1 = new javax.swing.JButton();
		jLabel2 = new javax.swing.JLabel();
		jButton2 = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jPanel1.setBackground(new java.awt.Color(255, 255, 255));

		jLabel1.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 20));
		jLabel1.setText("\u8bf7\u8f93\u5165\u8981\u4fee\u6539\u7684\u7269\u54c1\u540d\u79f0\uff1a");

		jButton1.setBackground(new java.awt.Color(51, 102, 255));
		jButton1.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 20));
		jButton1.setForeground(new java.awt.Color(255, 255, 255));
		jButton1.setText("\u786e\u5b9a");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/img/1.png"))); // NOI18N

		jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/img/exitlogo.png"))); // NOI18N
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton2ActionPerformed(evt);
			}
		});

		org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(
				jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout
				.setHorizontalGroup(jPanel1Layout
						.createParallelGroup(
								org.jdesktop.layout.GroupLayout.LEADING)
						.add(jPanel1Layout
								.createSequentialGroup()
								.add(jLabel2)
								.add(jPanel1Layout
										.createParallelGroup(
												org.jdesktop.layout.GroupLayout.TRAILING)
										.add(jPanel1Layout
												.createSequentialGroup()
												.add(jPanel1Layout
														.createParallelGroup(
																org.jdesktop.layout.GroupLayout.LEADING)
														.add(jPanel1Layout
																.createSequentialGroup()
																.add(159, 159,
																		159)
																.add(jButton1))
														.add(jPanel1Layout
																.createSequentialGroup()
																.add(68, 68, 68)
																.add(jPanel1Layout
																		.createParallelGroup(
																				org.jdesktop.layout.GroupLayout.LEADING)
																		.add(jTextField1,
																				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																				266,
																				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
																		.add(jLabel1,
																				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																				317,
																				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
												.addContainerGap(26,
														Short.MAX_VALUE))
										.add(jPanel1Layout
												.createSequentialGroup()
												.addPreferredGap(
														org.jdesktop.layout.LayoutStyle.RELATED)
												.add(jButton2,
														org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
														58,
														org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
												.addContainerGap()))));
		jPanel1Layout.setVerticalGroup(jPanel1Layout
				.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
				.add(jPanel1Layout
						.createSequentialGroup()
						.addContainerGap()
						.add(jButton2,
								org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
								55,
								org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
						.add(57, 57, 57)
						.add(jLabel1,
								org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
								35,
								org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
						.add(48, 48, 48)
						.add(jTextField1,
								org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
								50,
								org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
						.add(28, 28, 28).add(jButton1)).add(jLabel2));

		org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				org.jdesktop.layout.GroupLayout.LEADING).add(
				org.jdesktop.layout.GroupLayout.TRAILING, jPanel1,
				org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
				org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
		layout.setVerticalGroup(layout.createParallelGroup(
				org.jdesktop.layout.GroupLayout.LEADING).add(jPanel1,
				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 436,
				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
		new AdminUI().setVisible(true);
		this.dispose();
	}

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
		new ModifySelectUI().setVisible(true);
		this.dispose();
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new Change().setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JTextField jTextField1;
	// End of variables declaration//GEN-END:variables

}