/*
 * CommentCenter.java
 *
 * Created on __DATE__, __TIME__
 */

package view;

import java.util.ArrayList;

import javax.swing.table.DefaultTableModel;

import Data.CRUD;
import Data.comments;

/**
 *
 * @author  __USER__
 */
public class CommentCenter extends javax.swing.JFrame {

	/**
	 * 
	 */
	private static final long serialVersionUID = 2775650597998853400L;
	/** Creates new form CommentCenter */
	public CommentCenter() {
		initComponents();
		init();
		setLocationRelativeTo(null);
	}

	private void init() {
		ArrayList<comments> leaves = CRUD.getComment();
		String[] columnNames = { "物品名称", "评价详情" };
		Object[][] detail = new Object[leaves.size()][2];
		for (int i = 0; i < leaves.size(); i++) {

			detail[i][0] = leaves.get(i).getGn();
			detail[i][1] = leaves.get(i).getUcomment();

		}
		this.jTable1.setModel(new DefaultTableModel(detail, columnNames));
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		jScrollPane1 = new javax.swing.JScrollPane();
		jTable1 = new javax.swing.JTable();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jButton1 = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jPanel1.setBackground(new java.awt.Color(255, 255, 255));

		jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/img/bigui.png"))); // NOI18N

		jTable1.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14));
		jTable1.setModel(new javax.swing.table.DefaultTableModel(
				new Object[][] { { null, null }, { null, null },
						{ null, null }, { null, null } }, new String[] {
						"物品名称", "评价详情" }));
		jScrollPane1.setViewportView(jTable1);

		jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/img/logo.png"))); // NOI18N

		jLabel3.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 20));
		jLabel3.setText("\u8bc4\u4ef7\u4e2d\u5fc3");

		jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/img/exitlogo.png"))); // NOI18N
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(
				jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout
				.setHorizontalGroup(jPanel1Layout
						.createParallelGroup(
								org.jdesktop.layout.GroupLayout.LEADING)
						.add(jPanel1Layout
								.createSequentialGroup()
								.add(jLabel1,
										org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
										org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE)
								.add(jPanel1Layout
										.createParallelGroup(
												org.jdesktop.layout.GroupLayout.LEADING)
										.add(jPanel1Layout
												.createSequentialGroup()
												.addPreferredGap(
														org.jdesktop.layout.LayoutStyle.RELATED)
												.add(jLabel2)
												.addPreferredGap(
														org.jdesktop.layout.LayoutStyle.RELATED)
												.add(jLabel3)
												.addPreferredGap(
														org.jdesktop.layout.LayoutStyle.RELATED,
														685, Short.MAX_VALUE)
												.add(jButton1,
														org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
														66,
														org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
												.add(22, 22, 22))
										.add(jPanel1Layout
												.createSequentialGroup()
												.add(102, 102, 102)
												.add(jScrollPane1,
														org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
														782,
														org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
												.addContainerGap()))));
		jPanel1Layout
				.setVerticalGroup(jPanel1Layout
						.createParallelGroup(
								org.jdesktop.layout.GroupLayout.LEADING)
						.add(jLabel1,
								org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
								org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
								Short.MAX_VALUE)
						.add(jPanel1Layout
								.createSequentialGroup()
								.add(jPanel1Layout
										.createParallelGroup(
												org.jdesktop.layout.GroupLayout.LEADING)
										.add(jLabel2,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
												100,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
										.add(jPanel1Layout
												.createSequentialGroup()
												.add(41, 41, 41).add(jLabel3))
										.add(jPanel1Layout
												.createSequentialGroup()
												.add(24, 24, 24)
												.add(jButton1,
														org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
														65,
														org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
								.addPreferredGap(
										org.jdesktop.layout.LayoutStyle.UNRELATED)
								.add(jScrollPane1,
										org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
										574, Short.MAX_VALUE).add(42, 42, 42)));

		org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				org.jdesktop.layout.GroupLayout.LEADING).add(jPanel1,
				org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
				org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
		layout.setVerticalGroup(layout.createParallelGroup(
				org.jdesktop.layout.GroupLayout.LEADING).add(jPanel1,
				org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
				org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
		new User().setVisible(true);
		this.dispose();
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new CommentCenter().setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton jButton1;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTable jTable1;
	// End of variables declaration//GEN-END:variables

}