/*
 * Change.java
 *
 * Created on __DATE__, __TIME__
 */

package view;

import javax.swing.JOptionPane;

import Data.CRUD;
import java.io.OutputStream;
import java.io.PrintStream;
import javax.swing.text.JTextComponent;
import javax.swing.SwingUtilities;

/**
 * 
 * @author __USER__
 */
public class Delete extends javax.swing.JFrame {

	/**
	 * 
	 */

	/**
	 * 
	 */
	private static final long serialVersionUID = 1212597964555291288L;
	/** Creates new form Change */
	public Delete() {
		initComponents();
		MyPrintStream mps = new MyPrintStream(System.out, jTextField1);
		System.setOut(mps);
		System.setErr(mps);

		this.setLocationRelativeTo(null);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		jTextField1 = new javax.swing.JTextField();
		jButton1 = new javax.swing.JButton();
		jLabel2 = new javax.swing.JLabel();
		jButton2 = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jPanel1.setBackground(new java.awt.Color(255, 255, 255));

		jLabel1.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 20));
		jLabel1.setText("\u8bf7\u8f93\u5165\u8981\u5220\u9664\u7684\u7269\u54c1\u540d\u79f0\uff1a");

		jTextField1.setEditable(false);
		jTextField1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jTextField1ActionPerformed(evt);
			}
		});

		jButton1.setBackground(new java.awt.Color(51, 102, 255));
		jButton1.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 20));
		jButton1.setForeground(new java.awt.Color(255, 255, 255));
		jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/img/confirmbutton.png"))); // NOI18N
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/img/1.png"))); // NOI18N

		jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/img/exitlogo.png"))); // NOI18N
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton2ActionPerformed(evt);
			}
		});

		org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(
				jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout
				.setHorizontalGroup(jPanel1Layout
						.createParallelGroup(
								org.jdesktop.layout.GroupLayout.LEADING)
						.add(jPanel1Layout
								.createSequentialGroup()
								.add(jLabel2)
								.add(jPanel1Layout
										.createParallelGroup(
												org.jdesktop.layout.GroupLayout.LEADING)
										.add(jPanel1Layout
												.createParallelGroup(
														org.jdesktop.layout.GroupLayout.TRAILING)
												.add(jPanel1Layout
														.createSequentialGroup()
														.add(66, 66, 66)
														.add(jPanel1Layout
																.createParallelGroup(
																		org.jdesktop.layout.GroupLayout.LEADING)
																.add(jLabel1,
																		org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																		317,
																		org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
																.add(jTextField1,
																		org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																		266,
																		org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
														.addContainerGap(28,
																Short.MAX_VALUE))
												.add(jPanel1Layout
														.createSequentialGroup()
														.addPreferredGap(
																org.jdesktop.layout.LayoutStyle.RELATED)
														.add(jButton2,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																56,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
														.addContainerGap()))
										.add(jPanel1Layout
												.createSequentialGroup()
												.add(157, 157, 157)
												.add(jButton1,
														org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
														89,
														org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
												.addContainerGap()))));
		jPanel1Layout
				.setVerticalGroup(jPanel1Layout
						.createParallelGroup(
								org.jdesktop.layout.GroupLayout.LEADING)
						.add(jPanel1Layout
								.createSequentialGroup()
								.addContainerGap()
								.add(jButton2,
										org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
										52,
										org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
								.add(54, 54, 54)
								.add(jLabel1,
										org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
										35,
										org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
								.add(33, 33, 33)
								.add(jTextField1,
										org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
										50,
										org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
								.add(38, 38, 38)
								.add(jButton1,
										org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
										43,
										org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
						.add(jLabel2));

		org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				org.jdesktop.layout.GroupLayout.LEADING).add(
				org.jdesktop.layout.GroupLayout.TRAILING, jPanel1,
				org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
				org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
		layout.setVerticalGroup(layout.createParallelGroup(
				org.jdesktop.layout.GroupLayout.LEADING).add(jPanel1,
				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 435,
				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	public class MyPrintStream extends PrintStream {

		private JTextComponent text;
		private StringBuffer sb = new StringBuffer();

		public MyPrintStream(OutputStream out, JTextComponent text) {
			super(out);
			this.text = text;
		}

		/**
		 * 在这里重截,所有的打印方法都要调用的方法
		 */
		public void write(byte[] buf, int off, int len) {
			final String message = new String(buf, off, len);
			SwingUtilities.invokeLater(new Runnable() {
				public void run() {
					sb.append(message + "\n");
					text.setText(sb.toString());
				}
			});
		}
	}

	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
		new DeleteUI().setVisible(true);
		this.dispose();
	}

	private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {

		// TODO add your handling code here:
	}

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
		boolean b = CRUD.deleteGood(jTextField1.getText());
		if (b) {
			JOptionPane.showMessageDialog(this, "删除成功！");
		} else
			JOptionPane.showMessageDialog(this, "删除失败！");

		new DeleteUI().setVisible(true);
		this.dispose();
	}

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new Delete().setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JTextField jTextField1;
	// End of variables declaration//GEN-END:variables

}