/*
 * Login.java
 *
 * Created on __DATE__, __TIME__
 */

package view;

import javax.swing.JOptionPane;
import Data.CRUD;

/**
 *
 * @author  __USER__
 */
public class Login extends javax.swing.JFrame {

	/**
	 * 
	 */
	private static final long serialVersionUID = -1584960543340193729L;
	/** Creates new form Login */
	public Login() {
		initComponents();
		setLocationRelativeTo(null);
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jFrame1 = new javax.swing.JFrame();
		buttonGroup1 = new javax.swing.ButtonGroup();
		jPanel1 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		jTextField1 = new javax.swing.JTextField();
		jPasswordField1 = new javax.swing.JPasswordField();
		jRadioButton1 = new javax.swing.JRadioButton();
		jRadioButton2 = new javax.swing.JRadioButton();
		jButton1 = new javax.swing.JButton();
		jLabel5 = new javax.swing.JLabel();
		jButton2 = new javax.swing.JButton();

		org.jdesktop.layout.GroupLayout jFrame1Layout = new org.jdesktop.layout.GroupLayout(
				jFrame1.getContentPane());
		jFrame1.getContentPane().setLayout(jFrame1Layout);
		jFrame1Layout.setHorizontalGroup(jFrame1Layout.createParallelGroup(
				org.jdesktop.layout.GroupLayout.LEADING).add(0, 400,
				Short.MAX_VALUE));
		jFrame1Layout.setVerticalGroup(jFrame1Layout.createParallelGroup(
				org.jdesktop.layout.GroupLayout.LEADING).add(0, 300,
				Short.MAX_VALUE));

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jPanel1.setBackground(new java.awt.Color(255, 255, 255));

		jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/img/1.png"))); // NOI18N

		jLabel2.setFont(new java.awt.Font("ºÚÌå", 1, 30));
		jLabel2.setText("\u6b22\u8fce\u767b\u5f55");

		jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/img/bar.png"))); // NOI18N

		jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/img/2.png"))); // NOI18N

		jTextField1.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18));
		jTextField1.setBorder(new javax.swing.border.LineBorder(
				new java.awt.Color(57, 98, 214), 1, true));

		jPasswordField1.setFont(new java.awt.Font("ËÎÌå", 0, 18));
		jPasswordField1.setBorder(new javax.swing.border.LineBorder(
				new java.awt.Color(57, 98, 214), 1, true));

		jRadioButton1.setBackground(new java.awt.Color(255, 255, 255));
		buttonGroup1.add(jRadioButton1);
		jRadioButton1.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 16));
		jRadioButton1.setText("\u7528\u6237");
		jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jRadioButton1ActionPerformed(evt);
			}
		});

		jRadioButton2.setBackground(new java.awt.Color(255, 255, 255));
		buttonGroup1.add(jRadioButton2);
		jRadioButton2.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 16));
		jRadioButton2.setText("\u7ba1\u7406\u5458");

		jButton1.setBackground(new java.awt.Color(255, 255, 255));
		jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/img/button.png"))); // NOI18N
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/img/logo.png"))); // NOI18N

		jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/img/registerbutton.png"))); // NOI18N
		jButton2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1,
				1));
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton2ActionPerformed(evt);
			}
		});

		org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(
				jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout
				.setHorizontalGroup(jPanel1Layout
						.createParallelGroup(
								org.jdesktop.layout.GroupLayout.LEADING)
						.add(jPanel1Layout
								.createSequentialGroup()
								.add(jLabel1)
								.add(jPanel1Layout
										.createParallelGroup(
												org.jdesktop.layout.GroupLayout.LEADING)
										.add(jPanel1Layout
												.createSequentialGroup()
												.add(36, 36, 36)
												.add(jLabel4)
												.addPreferredGap(
														org.jdesktop.layout.LayoutStyle.RELATED)
												.add(jPanel1Layout
														.createParallelGroup(
																org.jdesktop.layout.GroupLayout.LEADING)
														.add(org.jdesktop.layout.GroupLayout.TRAILING,
																jPanel1Layout
																		.createSequentialGroup()
																		.add(66,
																				66,
																				66)
																		.add(jLabel3,
																				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																				210,
																				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
																		.add(156,
																				156,
																				156))
														.add(jPanel1Layout
																.createSequentialGroup()
																.add(jPanel1Layout
																		.createParallelGroup(
																				org.jdesktop.layout.GroupLayout.TRAILING)
																		.add(org.jdesktop.layout.GroupLayout.LEADING,
																				jPasswordField1,
																				org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																				352,
																				Short.MAX_VALUE)
																		.add(org.jdesktop.layout.GroupLayout.LEADING,
																				jPanel1Layout
																						.createSequentialGroup()
																						.addPreferredGap(
																								org.jdesktop.layout.LayoutStyle.RELATED)
																						.add(jTextField1,
																								org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																								352,
																								Short.MAX_VALUE))
																		.add(org.jdesktop.layout.GroupLayout.LEADING,
																				jPanel1Layout
																						.createSequentialGroup()
																						.add(12,
																								12,
																								12)
																						.add(jButton1,
																								org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																								298,
																								org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
																		.add(org.jdesktop.layout.GroupLayout.LEADING,
																				jPanel1Layout
																						.createSequentialGroup()
																						.add(jRadioButton1)
																						.addPreferredGap(
																								org.jdesktop.layout.LayoutStyle.RELATED,
																								84,
																								Short.MAX_VALUE)
																						.add(jRadioButton2)
																						.add(52,
																								52,
																								52)
																						.add(jButton2,
																								org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																								63,
																								org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
																						.add(23,
																								23,
																								23)))
																.addContainerGap(
																		85,
																		Short.MAX_VALUE))))
										.add(jPanel1Layout
												.createSequentialGroup()
												.add(18, 18, 18)
												.add(jLabel5,
														org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
														90,
														org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
												.add(110, 110, 110)
												.add(jLabel2,
														org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
														218,
														org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
												.addContainerGap()))));
		jPanel1Layout
				.setVerticalGroup(jPanel1Layout
						.createParallelGroup(
								org.jdesktop.layout.GroupLayout.LEADING)
						.add(jLabel1)
						.add(jPanel1Layout
								.createSequentialGroup()
								.add(17, 17, 17)
								.add(jPanel1Layout
										.createParallelGroup(
												org.jdesktop.layout.GroupLayout.TRAILING)
										.add(jLabel2,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
												51,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
										.add(jLabel5,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
												95,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(
										org.jdesktop.layout.LayoutStyle.RELATED)
								.add(jPanel1Layout
										.createParallelGroup(
												org.jdesktop.layout.GroupLayout.LEADING)
										.add(jPanel1Layout
												.createSequentialGroup()
												.add(jLabel3)
												.add(32, 32, 32)
												.add(jTextField1,
														org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
														39,
														org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
												.addPreferredGap(
														org.jdesktop.layout.LayoutStyle.UNRELATED)
												.add(jPasswordField1,
														org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
														41,
														org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
												.add(jPanel1Layout
														.createParallelGroup(
																org.jdesktop.layout.GroupLayout.LEADING)
														.add(jPanel1Layout
																.createSequentialGroup()
																.add(12, 12, 12)
																.add(jPanel1Layout
																		.createParallelGroup(
																				org.jdesktop.layout.GroupLayout.BASELINE)
																		.add(jRadioButton1)
																		.add(jRadioButton2)))
														.add(jPanel1Layout
																.createSequentialGroup()
																.add(18, 18, 18)
																.add(jButton2,
																		org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																		19,
																		org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
										.add(jLabel4,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
												175,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
								.add(18, 18, 18)
								.add(jButton1,
										org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
										40,
										org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)));

		org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				org.jdesktop.layout.GroupLayout.LEADING).add(jPanel1,
				org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
				org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
		layout.setVerticalGroup(layout.createParallelGroup(
				org.jdesktop.layout.GroupLayout.LEADING).add(jPanel1,
				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
				org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
		new Register(null).setVisible(true);
		this.dispose();
	}

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
		String id = jTextField1.getText();
		@SuppressWarnings("deprecation")
		String pwd = jPasswordField1.getText();
		if (jRadioButton1.isSelected()) {
			boolean flag = CRUD.userQuery(id, pwd);
			if (flag) {
				JOptionPane.showMessageDialog(this, "µÇÂ¼³É¹¦");
				new User().setVisible(true);

				this.dispose();
			} else {
				JOptionPane.showMessageDialog(this, "µÇÂ¼Ê§°Ü");
			}
		}
		if (jRadioButton2.isSelected()) {
			boolean flag = CRUD.userQuery(id, pwd);
			if (flag) {
				JOptionPane.showMessageDialog(this, "µÇÂ¼³É¹¦");
				new Admin().setVisible(true);

				this.dispose();
			} else {
				JOptionPane.showMessageDialog(this, "µÇÂ¼Ê§°Ü");
			}
		}

	}

	private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new Login().setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.ButtonGroup buttonGroup1;
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JFrame jFrame1;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPasswordField jPasswordField1;
	private javax.swing.JRadioButton jRadioButton1;
	private javax.swing.JRadioButton jRadioButton2;
	private javax.swing.JTextField jTextField1;
	// End of variables declaration//GEN-END:variables

}