/*
 * ModifySelectUI.java
 *
 * Created on __DATE__, __TIME__
 */

package view;

import java.util.ArrayList;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import Data.CRUD;
import Data.goods;

/**
 *
 * @author  __USER__
 */
public class ModifySelectUI extends javax.swing.JFrame {

	/**
	 * 
	 */
	private static final long serialVersionUID = 9095837579931996161L;
	/** Creates new form ModifySelectUI */
	public ModifySelectUI() {
		initComponents();
		init();
		setLocationRelativeTo(null);
	}
	
	private void init() {
		ArrayList<goods> goodss = CRUD.foundGood("");
		String[] columnName = {"物品名称","物品类型","物品费用","物品库存"};
		Object[][] rowdata = new Object[goodss.size()][columnName.length];
		for(int i= 0;i<rowdata.length; i++){
			rowdata[i][0] = goodss.get(i).getGname();
			rowdata[i][1] = goodss.get(i).getgType();
			rowdata[i][2] = goodss.get(i).getGamount();
			rowdata[i][3] = goodss.get(i).getGstock();
			
		}
		jTable1.setModel(new DefaultTableModel(rowdata, columnName));
		                                               
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jButton5 = new javax.swing.JButton();
		jScrollPane1 = new javax.swing.JScrollPane();
		jTable1 = new javax.swing.JTable();
		jButton1 = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jPanel1.setBackground(new java.awt.Color(255, 255, 255));

		jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/img/bigui.png"))); // NOI18N

		jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/img/logo.png"))); // NOI18N

		jLabel3.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 20));
		jLabel3.setText("\u9009\u62e9\u7269\u54c1\u8fdb\u884c\u4fee\u6539");

		jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/img/exitlogo.png"))); // NOI18N
		jButton5.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton5ActionPerformed(evt);
			}
		});

		jTable1.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18));
		jTable1.setModel(new javax.swing.table.DefaultTableModel(
				new Object[][] { { null, null, null, null },
						{ null, null, null, null }, { null, null, null, null },
						{ null, null, null, null }, { null, null, null, null },
						{ null, null, null, null }, { null, null, null, null },
						{ null, null, null, null }, { null, null, null, null },
						{ null, null, null, null }, { null, null, null, null },
						{ null, null, null, null }, { null, null, null, null },
						{ null, null, null, null }, { null, null, null, null },
						{ null, null, null, null }, { null, null, null, null },
						{ null, null, null, null }, { null, null, null, null },
						{ null, null, null, null }, { null, null, null, null },
						{ null, null, null, null }, { null, null, null, null },
						{ null, null, null, null }, { null, null, null, null },
						{ null, null, null, null }, { null, null, null, null },
						{ null, null, null, null }, { null, null, null, null },
						{ null, null, null, null }, { null, null, null, null },
						{ null, null, null, null }, { null, null, null, null },
						{ null, null, null, null }, { null, null, null, null },
						{ null, null, null, null }, { null, null, null, null },
						{ null, null, null, null }, { null, null, null, null },
						{ null, null, null, null }, { null, null, null, null },
						{ null, null, null, null }, { null, null, null, null },
						{ null, null, null, null }, { null, null, null, null },
						{ null, null, null, null }, { null, null, null, null },
						{ null, null, null, null }, { null, null, null, null },
						{ null, null, null, null }, { null, null, null, null },
						{ null, null, null, null }, { null, null, null, null },
						{ null, null, null, null }, { null, null, null, null },
						{ null, null, null, null }, { null, null, null, null },
						{ null, null, null, null }, { null, null, null, null },
						{ null, null, null, null }, { null, null, null, null },
						{ null, null, null, null }, { null, null, null, null },
						{ null, null, null, null }, { null, null, null, null },
						{ null, null, null, null }, { null, null, null, null },
						{ null, null, null, null }, { null, null, null, null },
						{ null, null, null, null }, { null, null, null, null },
						{ null, null, null, null }, { null, null, null, null },
						{ null, null, null, null }, { null, null, null, null },
						{ null, null, null, null }, { null, null, null, null },
						{ null, null, null, null }, { null, null, null, null },
						{ null, null, null, null }, { null, null, null, null },
						{ null, null, null, null }, { null, null, null, null },
						{ null, null, null, null }, { null, null, null, null },
						{ null, null, null, null }, { null, null, null, null },
						{ null, null, null, null }, { null, null, null, null },
						{ null, null, null, null }, { null, null, null, null },
						{ null, null, null, null }, { null, null, null, null },
						{ null, null, null, null }, { null, null, null, null },
						{ null, null, null, null }, { null, null, null, null },
						{ null, null, null, null }, { null, null, null, null },
						{ null, null, null, null } }, new String[] { "名称",
						"类型", "租金", "库存" }));
		jScrollPane1.setViewportView(jTable1);

		jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/img/confirmbutton.png"))); // NOI18N
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(
				jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout
				.setHorizontalGroup(jPanel1Layout
						.createParallelGroup(
								org.jdesktop.layout.GroupLayout.LEADING)
						.add(
								jPanel1Layout
										.createSequentialGroup()
										.add(
												jPanel1Layout
														.createParallelGroup(
																org.jdesktop.layout.GroupLayout.LEADING)
														.add(
																jPanel1Layout
																		.createSequentialGroup()
																		.add(
																				jLabel1,
																				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																				446,
																				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
																		.add(
																				jPanel1Layout
																						.createParallelGroup(
																								org.jdesktop.layout.GroupLayout.LEADING)
																						.add(
																								jPanel1Layout
																										.createParallelGroup(
																												org.jdesktop.layout.GroupLayout.LEADING)
																										.add(
																												jPanel1Layout
																														.createSequentialGroup()
																														.add(
																																7,
																																7,
																																7)
																														.add(
																																jLabel2))
																										.add(
																												org.jdesktop.layout.GroupLayout.TRAILING,
																												jPanel1Layout
																														.createSequentialGroup()
																														.addPreferredGap(
																																org.jdesktop.layout.LayoutStyle.RELATED,
																																86,
																																Short.MAX_VALUE)
																														.add(
																																jScrollPane1,
																																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																																1000,
																																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
																														.addPreferredGap(
																																org.jdesktop.layout.LayoutStyle.RELATED)))
																						.add(
																								org.jdesktop.layout.GroupLayout.TRAILING,
																								jPanel1Layout
																										.createSequentialGroup()
																										.addPreferredGap(
																												org.jdesktop.layout.LayoutStyle.RELATED)
																										.add(
																												jButton1,
																												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																												154,
																												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
																										.add(
																												432,
																												432,
																												432))))
														.add(
																jPanel1Layout
																		.createSequentialGroup()
																		.add(
																				559,
																				559,
																				559)
																		.add(
																				jLabel3)))
										.addPreferredGap(
												org.jdesktop.layout.LayoutStyle.RELATED,
												8, Short.MAX_VALUE)
										.add(
												jButton5,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
												60,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
										.addContainerGap()));
		jPanel1Layout
				.setVerticalGroup(jPanel1Layout
						.createParallelGroup(
								org.jdesktop.layout.GroupLayout.LEADING)
						.add(jLabel1)
						.add(
								jPanel1Layout
										.createSequentialGroup()
										.add(
												jPanel1Layout
														.createParallelGroup(
																org.jdesktop.layout.GroupLayout.LEADING)
														.add(
																jPanel1Layout
																		.createSequentialGroup()
																		.add(
																				34,
																				34,
																				34)
																		.add(
																				jLabel3))
														.add(
																jLabel2,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																93,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
										.add(12, 12, 12)
										.add(
												jScrollPane1,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
												536,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												org.jdesktop.layout.LayoutStyle.UNRELATED)
										.add(
												jButton1,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
												51,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
						.add(
								jPanel1Layout
										.createSequentialGroup()
										.addContainerGap()
										.add(
												jButton5,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
												59,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)));

		org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				org.jdesktop.layout.GroupLayout.LEADING).add(jPanel1,
				org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
				org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
		layout.setVerticalGroup(layout.createParallelGroup(
				org.jdesktop.layout.GroupLayout.LEADING).add(jPanel1,
				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 722,
				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
		String gname = JOptionPane.showInputDialog(this, "请输入要修改的物品信息");
		
		if (gname.equals("")){
			JOptionPane.showMessageDialog(this, "请输入物品名称");
		}
		else {
			new ModifyUI(gname).setVisible(true);
			this.dispose();
		}
	}

	private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {
		new AdminUI().setVisible(true);
		this.dispose();
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new ModifySelectUI().setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton5;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTable jTable1;
	// End of variables declaration//GEN-END:variables

}