/*
 * Register.java
 *
 * Created on __DATE__, __TIME__
 */

package view;

import javax.swing.JOptionPane;

import Data.CRUD;
import Data.user;

/**
 *
 * @author  __USER__
 */
public class Register extends javax.swing.JFrame {

	/**
	 * 
	 */
	private static final long serialVersionUID = -7844905949493067385L;
	Login m;

	/** Creates new form Register */
	public Register(Login m) {
		initComponents();
		setLocationRelativeTo(null);
		this.m = m;
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jTextField1 = new javax.swing.JTextField();
		jPasswordField1 = new javax.swing.JPasswordField();
		jPasswordField2 = new javax.swing.JPasswordField();
		jLabel4 = new javax.swing.JLabel();
		jLabel5 = new javax.swing.JLabel();
		jLabel6 = new javax.swing.JLabel();
		jButton1 = new javax.swing.JButton();
		jButton2 = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jPanel1.setBackground(new java.awt.Color(255, 255, 255));

		jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/img/1.png"))); // NOI18N

		jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/img/logo.png"))); // NOI18N

		jLabel3.setFont(new java.awt.Font("黑体", 1, 30));
		jLabel3.setText("\u6ce8\u518c");

		jTextField1.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18));

		jPasswordField1.setFont(new java.awt.Font("宋体", 0, 18));

		jPasswordField2.setFont(new java.awt.Font("宋体", 0, 18));

		jLabel4.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18));
		jLabel4.setText("\u8d26\u53f7\uff1a");

		jLabel5.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18));
		jLabel5.setText("\u5bc6\u7801\uff1a");

		jLabel6.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18));
		jLabel6.setText("\u786e\u8ba4\u5bc6\u7801\uff1a");

		jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/img/confirmbutton.png"))); // NOI18N
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/img/exitlogo.png"))); // NOI18N
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton2ActionPerformed(evt);
			}
		});

		org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(
				jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout
				.setHorizontalGroup(jPanel1Layout
						.createParallelGroup(
								org.jdesktop.layout.GroupLayout.LEADING)
						.add(jPanel1Layout
								.createSequentialGroup()
								.add(jLabel1)
								.add(jPanel1Layout
										.createParallelGroup(
												org.jdesktop.layout.GroupLayout.LEADING)
										.add(jPanel1Layout
												.createSequentialGroup()
												.add(jPanel1Layout
														.createParallelGroup(
																org.jdesktop.layout.GroupLayout.LEADING)
														.add(jPanel1Layout
																.createSequentialGroup()
																.add(34, 34, 34)
																.add(jPanel1Layout
																		.createParallelGroup(
																				org.jdesktop.layout.GroupLayout.LEADING,
																				false)
																		.add(jPanel1Layout
																				.createSequentialGroup()
																				.add(jLabel6)
																				.addPreferredGap(
																						org.jdesktop.layout.LayoutStyle.RELATED))
																		.add(org.jdesktop.layout.GroupLayout.TRAILING,
																				jPanel1Layout
																						.createSequentialGroup()
																						.addPreferredGap(
																								org.jdesktop.layout.LayoutStyle.RELATED,
																								28,
																								org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
																						.add(jPanel1Layout
																								.createParallelGroup(
																										org.jdesktop.layout.GroupLayout.LEADING)
																								.add(jLabel4)
																								.add(jLabel5))
																						.add(26,
																								26,
																								26)))
																.add(jPanel1Layout
																		.createParallelGroup(
																				org.jdesktop.layout.GroupLayout.LEADING,
																				false)
																		.add(jPasswordField1)
																		.add(jPasswordField2)
																		.add(jTextField1,
																				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																				264,
																				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
																.addPreferredGap(
																		org.jdesktop.layout.LayoutStyle.RELATED,
																		org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																		Short.MAX_VALUE))
														.add(jPanel1Layout
																.createSequentialGroup()
																.addPreferredGap(
																		org.jdesktop.layout.LayoutStyle.RELATED)
																.add(jLabel2,
																		org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																		90,
																		org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
																.addPreferredGap(
																		org.jdesktop.layout.LayoutStyle.RELATED,
																		137,
																		Short.MAX_VALUE)
																.add(jLabel3,
																		org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																		100,
																		org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
																.add(91, 91, 91)))
												.add(23, 23, 23)
												.add(jButton2,
														org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
														60,
														org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
												.addContainerGap())
										.add(org.jdesktop.layout.GroupLayout.TRAILING,
												jPanel1Layout
														.createSequentialGroup()
														.addPreferredGap(
																org.jdesktop.layout.LayoutStyle.RELATED)
														.add(jButton1,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																89,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
														.add(209, 209, 209)))));
		jPanel1Layout
				.setVerticalGroup(jPanel1Layout
						.createParallelGroup(
								org.jdesktop.layout.GroupLayout.LEADING)
						.add(jLabel1,
								org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
								org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
								Short.MAX_VALUE)
						.add(jPanel1Layout
								.createSequentialGroup()
								.addContainerGap()
								.add(jPanel1Layout
										.createParallelGroup(
												org.jdesktop.layout.GroupLayout.TRAILING)
										.add(jLabel3,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
												43,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
										.add(jPanel1Layout
												.createParallelGroup(
														org.jdesktop.layout.GroupLayout.LEADING)
												.add(jButton2,
														org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
														55,
														org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
												.add(jLabel2,
														org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
														90,
														org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
								.add(29, 29, 29)
								.add(jPanel1Layout
										.createParallelGroup(
												org.jdesktop.layout.GroupLayout.BASELINE)
										.add(jLabel4,
												org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
												59, Short.MAX_VALUE)
										.add(jTextField1,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
												34,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
								.add(31, 31, 31)
								.add(jPanel1Layout
										.createParallelGroup(
												org.jdesktop.layout.GroupLayout.TRAILING)
										.add(jLabel5,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
												33,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
										.add(jPasswordField1,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
												36,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
								.add(41, 41, 41)
								.add(jPanel1Layout
										.createParallelGroup(
												org.jdesktop.layout.GroupLayout.TRAILING)
										.add(jLabel6,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
												34,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
										.add(jPasswordField2,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
												38,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
								.add(46, 46, 46)
								.add(jButton1,
										org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
										35,
										org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
								.add(25, 25, 25)));

		org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				org.jdesktop.layout.GroupLayout.LEADING).add(jPanel1,
				org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
				org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
		layout.setVerticalGroup(layout.createParallelGroup(
				org.jdesktop.layout.GroupLayout.LEADING).add(jPanel1,
				org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
				org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
		String uid = jTextField1.getText();
		String upassword = jPasswordField1.getText();

		CRUD.addUser(uid, upassword);
		JOptionPane.showMessageDialog(this, "注册成功");
		new Login().setVisible(true);
		this.dispose();
	}

	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
		new Login().setVisible(true);
		this.dispose();
	}

	/**
	 * @param args the command line arguments
	 */

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new Register(null).setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPasswordField jPasswordField1;
	private javax.swing.JPasswordField jPasswordField2;
	private javax.swing.JTextField jTextField1;
	// End of variables declaration//GEN-END:variables

}