/*
 * DeleteUI.java
 *
 * Created on __DATE__, __TIME__
 */

package view;

import java.sql.SQLException;
import java.util.ArrayList;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import Data.CRUD;
import Data.goods;
import Data.user;

/**
 *
 * @author  __USER__
 */
public class Search extends javax.swing.JFrame {
	String gname;
	String gType;

	/** Creates new form DeleteUI */
	public Search() {
		this.gname = gname;
		initComponents();
		init();
		setLocationRelativeTo(null);
	}
	
	private void init() {
		String msg = jTextField1.getText();
		Object[] titles = { "物品名称", "物品类型", "物品费用", "物品库存" };
		ArrayList<goods> Goods = CRUD.foundGood(msg);
		Object[][] detail = new Object[Goods.size()][4];
		for (int i = 0; i < Goods.size(); i++) {
			detail[i][0] = Goods.get(i).getGname();
			detail[i][1] = Goods.get(i).getgType();
			detail[i][2] = Goods.get(i).getGamount();
			detail[i][3] = Goods.get(i).getGstock();
		}
		jTable1.setModel(new DefaultTableModel(detail, titles));
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jButton5 = new javax.swing.JButton();
		jScrollPane1 = new javax.swing.JScrollPane();
		jTable1 = new javax.swing.JTable();
		jLabel4 = new javax.swing.JLabel();
		jTextField1 = new javax.swing.JTextField();
		jButton1 = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jPanel1.setBackground(new java.awt.Color(255, 255, 255));

		jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/img/bigui.png"))); // NOI18N

		jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/img/logo.png"))); // NOI18N

		jLabel3.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 20));
		jLabel3.setText("\u7269\u54c1\u8be6\u60c5");

		jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/img/exitlogo.png"))); // NOI18N
		jButton5.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton5ActionPerformed(evt);
			}
		});

		jTable1.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18));
		jTable1.setModel(new javax.swing.table.DefaultTableModel(
				new Object[][] { { null, null, null, null },
						{ null, null, null, null }, { null, null, null, null },
						{ null, null, null, null }, { null, null, null, null },
						{ null, null, null, null }, { null, null, null, null },
						{ null, null, null, null }, { null, null, null, null },
						{ null, null, null, null }, { null, null, null, null },
						{ null, null, null, null }, { null, null, null, null },
						{ null, null, null, null }, { null, null, null, null },
						{ null, null, null, null }, { null, null, null, null },
						{ null, null, null, null }, { null, null, null, null },
						{ null, null, null, null }, { null, null, null, null },
						{ null, null, null, null }, { null, null, null, null },
						{ null, null, null, null }, { null, null, null, null },
						{ null, null, null, null }, { null, null, null, null },
						{ null, null, null, null }, { null, null, null, null },
						{ null, null, null, null }, { null, null, null, null },
						{ null, null, null, null }, { null, null, null, null },
						{ null, null, null, null }, { null, null, null, null },
						{ null, null, null, null }, { null, null, null, null },
						{ null, null, null, null }, { null, null, null, null },
						{ null, null, null, null }, { null, null, null, null },
						{ null, null, null, null }, { null, null, null, null },
						{ null, null, null, null }, { null, null, null, null },
						{ null, null, null, null }, { null, null, null, null },
						{ null, null, null, null }, { null, null, null, null },
						{ null, null, null, null }, { null, null, null, null },
						{ null, null, null, null }, { null, null, null, null },
						{ null, null, null, null }, { null, null, null, null },
						{ null, null, null, null }, { null, null, null, null },
						{ null, null, null, null }, { null, null, null, null },
						{ null, null, null, null }, { null, null, null, null },
						{ null, null, null, null }, { null, null, null, null },
						{ null, null, null, null }, { null, null, null, null },
						{ null, null, null, null }, { null, null, null, null },
						{ null, null, null, null }, { null, null, null, null },
						{ null, null, null, null }, { null, null, null, null },
						{ null, null, null, null }, { null, null, null, null },
						{ null, null, null, null }, { null, null, null, null },
						{ null, null, null, null }, { null, null, null, null },
						{ null, null, null, null }, { null, null, null, null },
						{ null, null, null, null }, { null, null, null, null },
						{ null, null, null, null }, { null, null, null, null },
						{ null, null, null, null }, { null, null, null, null },
						{ null, null, null, null }, { null, null, null, null },
						{ null, null, null, null }, { null, null, null, null },
						{ null, null, null, null }, { null, null, null, null },
						{ null, null, null, null }, { null, null, null, null },
						{ null, null, null, null }, { null, null, null, null },
						{ null, null, null, null }, { null, null, null, null },
						{ null, null, null, null }, { null, null, null, null },
						{ null, null, null, null } }, new String[] { "名称",
						"类型", "租金", "库存" }));
		jTable1.setEnabled(false);
		jScrollPane1.setViewportView(jTable1);

		jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/img/deletelogo1.png"))); // NOI18N

		jButton1.setBackground(new java.awt.Color(51, 102, 255));
		jButton1.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 20));
		jButton1.setForeground(new java.awt.Color(255, 255, 255));
		jButton1.setText("\u67e5\u627e");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				try {
					jButton1ActionPerformed(evt);
				} catch (SQLException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
			}
		});

		org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(
				jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout
				.setHorizontalGroup(jPanel1Layout
						.createParallelGroup(
								org.jdesktop.layout.GroupLayout.LEADING)
						.add(
								jPanel1Layout
										.createSequentialGroup()
										.add(
												jLabel1,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
												446,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
										.add(
												jPanel1Layout
														.createParallelGroup(
																org.jdesktop.layout.GroupLayout.LEADING)
														.add(
																jPanel1Layout
																		.createSequentialGroup()
																		.add(
																				517,
																				517,
																				517)
																		.add(
																				jLabel4,
																				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																				57,
																				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
														.add(
																jPanel1Layout
																		.createSequentialGroup()
																		.add(
																				37,
																				37,
																				37)
																		.add(
																				jLabel2)
																		.add(
																				jPanel1Layout
																						.createParallelGroup(
																								org.jdesktop.layout.GroupLayout.LEADING)
																						.add(
																								jPanel1Layout
																										.createSequentialGroup()
																										.add(
																												7,
																												7,
																												7)
																										.add(
																												jLabel3)
																										.addPreferredGap(
																												org.jdesktop.layout.LayoutStyle.RELATED,
																												950,
																												Short.MAX_VALUE)
																										.add(
																												jButton5,
																												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																												60,
																												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
																						.add(
																								jPanel1Layout
																										.createSequentialGroup()
																										.add(
																												jTextField1,
																												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																												600,
																												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
																										.add(
																												45,
																												45,
																												45)
																										.add(
																												jButton1,
																												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																												85,
																												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
																						.add(
																								jScrollPane1,
																								org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																								795,
																								org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
										.addContainerGap()));
		jPanel1Layout
				.setVerticalGroup(jPanel1Layout
						.createParallelGroup(
								org.jdesktop.layout.GroupLayout.LEADING)
						.add(jLabel2)
						.add(jLabel1)
						.add(
								jPanel1Layout
										.createSequentialGroup()
										.add(14, 14, 14)
										.add(
												jPanel1Layout
														.createParallelGroup(
																org.jdesktop.layout.GroupLayout.TRAILING)
														.add(
																jPanel1Layout
																		.createSequentialGroup()
																		.add(
																				jPanel1Layout
																						.createParallelGroup(
																								org.jdesktop.layout.GroupLayout.TRAILING,
																								false)
																						.add(
																								jPanel1Layout
																										.createSequentialGroup()
																										.addPreferredGap(
																												org.jdesktop.layout.LayoutStyle.RELATED,
																												org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																												Short.MAX_VALUE)
																										.add(
																												jLabel3))
																						.add(
																								org.jdesktop.layout.GroupLayout.LEADING,
																								jPanel1Layout
																										.createSequentialGroup()
																										.addPreferredGap(
																												org.jdesktop.layout.LayoutStyle.RELATED)
																										.add(
																												jButton5,
																												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																												59,
																												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
																		.add(
																				43,
																				43,
																				43)
																		.add(
																				jTextField1,
																				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																				41,
																				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
														.add(
																jButton1,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																40,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
										.add(44, 44, 44)
										.add(
												jScrollPane1,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
												414,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
										.add(18, 18, 18)
										.add(
												jLabel4,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
												0,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)));

		org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				org.jdesktop.layout.GroupLayout.LEADING).add(
				org.jdesktop.layout.GroupLayout.TRAILING,
				layout.createSequentialGroup().addContainerGap(
						org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
						Short.MAX_VALUE).add(jPanel1,
						org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
						org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
						org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)));
		layout.setVerticalGroup(layout.createParallelGroup(
				org.jdesktop.layout.GroupLayout.LEADING).add(
				org.jdesktop.layout.GroupLayout.TRAILING,
				layout.createSequentialGroup().addContainerGap(
						org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
						Short.MAX_VALUE).add(jPanel1,
						org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 722,
						org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) throws SQLException {
	
		String msg = jTextField1.getText();
		Object[] titles = { "物品名称", "物品类型", "物品费用", "物品库存" };
		ArrayList<goods> Goods = CRUD.foundGood(msg);
		Object[][] detail = new Object[Goods.size()][4];
		for (int i = 0; i < Goods.size(); i++) {
			detail[i][0] = Goods.get(i).getGname();
			detail[i][1] = Goods.get(i).getgType();
			detail[i][2] = Goods.get(i).getGamount();
			detail[i][3] = Goods.get(i).getGstock();
		}
		jTable1.setModel(new DefaultTableModel(detail, titles));
	}

	private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {
		new AdminUI().setVisible(true);
		this.dispose();
	}

	/**
	 * @param args the command line arguments
	 */
	//	public static void main(String args[]) {
	//		java.awt.EventQueue.invokeLater(new Runnable() {
	//			public void run() {
	//				new Search(gname).setVisible(true);
	//			}
	//		});
	//	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton5;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTable jTable1;
	private javax.swing.JTextField jTextField1;
	// End of variables declaration//GEN-END:variables

}