/*
 * UserCommentUI.java
 *
 * Created on __DATE__, __TIME__
 */

package view;

import javax.swing.JOptionPane;
import java.io.OutputStream;
import java.io.PrintStream;
import javax.swing.text.JTextComponent;
import javax.swing.SwingUtilities;


import Data.CRUD;

/**
 *
 * @author  __USER__
 */
public class UserCommentUI extends javax.swing.JFrame {

	/**
	 * 
	 */
	private static final long serialVersionUID = 7580104978500688109L;

	/** Creates new form UserCommentUI */
	public UserCommentUI() {
		initComponents();
		MyPrintStream mps = new MyPrintStream(System.out, jTextField1);
		System.setOut(mps);
		System.setErr(mps);
		setLocationRelativeTo(null);
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jLabel7 = new javax.swing.JLabel();
		jButton2 = new javax.swing.JButton();
		jScrollPane1 = new javax.swing.JScrollPane();
		jTextArea1 = new javax.swing.JTextArea();
		jLabel3 = new javax.swing.JLabel();
		jButton1 = new javax.swing.JButton();
		jTextField1 = new javax.swing.JTextField();
		jLabel4 = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jPanel1.setBackground(new java.awt.Color(255, 255, 255));

		jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/img/bigui.png"))); // NOI18N

		jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/img/logo.png"))); // NOI18N

		jLabel7.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 20));
		jLabel7.setText("\u7269\u54c1\u8bc4\u4ef7\u9875\u9762");

		jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/img/exitlogo.png"))); // NOI18N
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton2ActionPerformed(evt);
			}
		});

		jTextArea1.setColumns(20);
		jTextArea1.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24));
		jTextArea1.setRows(5);
		jScrollPane1.setViewportView(jTextArea1);

		jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/img/commentlogo.png"))); // NOI18N

		jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/img/commentbutton2.png"))); // NOI18N
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		jTextField1.setEditable(false);
		jTextField1.setText("jTextField1");

		jLabel4.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18));
		jLabel4.setForeground(new java.awt.Color(58, 98, 215));
		jLabel4.setText("\u7269\u54c1\u540d\u79f0\uff1a");

		org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(
				jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout
				.setHorizontalGroup(jPanel1Layout
						.createParallelGroup(
								org.jdesktop.layout.GroupLayout.LEADING)
						.add(jPanel1Layout
								.createSequentialGroup()
								.add(jLabel1)
								.add(jPanel1Layout
										.createParallelGroup(
												org.jdesktop.layout.GroupLayout.LEADING)
										.add(jPanel1Layout
												.createSequentialGroup()
												.add(jPanel1Layout
														.createParallelGroup(
																org.jdesktop.layout.GroupLayout.LEADING)
														.add(jPanel1Layout
																.createSequentialGroup()
																.add(7, 7, 7)
																.add(jLabel2)
																.addPreferredGap(
																		org.jdesktop.layout.LayoutStyle.RELATED)
																.add(jLabel7,
																		org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																		139,
																		org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
																.addPreferredGap(
																		org.jdesktop.layout.LayoutStyle.RELATED,
																		498,
																		Short.MAX_VALUE)
																.add(jButton2,
																		org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																		86,
																		org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
														.add(jPanel1Layout
																.createSequentialGroup()
																.add(305, 305,
																		305)
																.add(jLabel3)
																.addPreferredGap(
																		org.jdesktop.layout.LayoutStyle.RELATED)
																.add(jButton1,
																		org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																		115,
																		org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
												.addContainerGap())
										.add(org.jdesktop.layout.GroupLayout.TRAILING,
												jPanel1Layout
														.createSequentialGroup()
														.add(164, 164, 164)
														.add(jPanel1Layout
																.createParallelGroup(
																		org.jdesktop.layout.GroupLayout.TRAILING,
																		false)
																.add(jPanel1Layout
																		.createSequentialGroup()
																		.add(jLabel4,
																				org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																				org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																				Short.MAX_VALUE)
																		.add(18,
																				18,
																				18)
																		.add(jTextField1,
																				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																				417,
																				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
																.add(jScrollPane1,
																		org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																		534,
																		org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
														.add(150, 150, 150)))));
		jPanel1Layout
				.setVerticalGroup(jPanel1Layout
						.createParallelGroup(
								org.jdesktop.layout.GroupLayout.LEADING)
						.add(jPanel1Layout
								.createSequentialGroup()
								.add(jPanel1Layout
										.createParallelGroup(
												org.jdesktop.layout.GroupLayout.LEADING)
										.add(jPanel1Layout
												.createSequentialGroup()
												.addContainerGap()
												.add(jLabel2,
														org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
														96,
														org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
										.add(jPanel1Layout
												.createSequentialGroup()
												.add(18, 18, 18)
												.add(jPanel1Layout
														.createParallelGroup(
																org.jdesktop.layout.GroupLayout.TRAILING)
														.add(jButton2,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																68,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
														.add(jLabel7,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																34,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
										.add(org.jdesktop.layout.GroupLayout.TRAILING,
												jPanel1Layout
														.createSequentialGroup()
														.addContainerGap(147,
																Short.MAX_VALUE)
														.add(jPanel1Layout
																.createParallelGroup(
																		org.jdesktop.layout.GroupLayout.BASELINE)
																.add(jTextField1,
																		org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																		34,
																		org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
																.add(jLabel4))
														.add(44, 44, 44)))
								.addPreferredGap(
										org.jdesktop.layout.LayoutStyle.RELATED)
								.add(jScrollPane1,
										org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
										271,
										org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
								.add(28, 28, 28)
								.add(jPanel1Layout
										.createParallelGroup(
												org.jdesktop.layout.GroupLayout.LEADING,
												false)
										.add(jLabel3, 0, 0, Short.MAX_VALUE)
										.add(jButton1,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
												59,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
								.add(43, 43, 43))
						.add(jLabel1,
								org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
								626, Short.MAX_VALUE));

		org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				org.jdesktop.layout.GroupLayout.LEADING).add(jPanel1,
				org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
				org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
		layout.setVerticalGroup(layout.createParallelGroup(
				org.jdesktop.layout.GroupLayout.LEADING).add(jPanel1,
				org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
				org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	public class MyPrintStream extends PrintStream {

		private JTextComponent text;
		private StringBuffer sb = new StringBuffer();

		public MyPrintStream(OutputStream out, JTextComponent text) {
			super(out);
			this.text = text;
		}

		/**
		 * 在这里重截,所有的打印方法都要调用的方法
		 */
		public void write(byte[] buf, int off, int len) {
			final String message = new String(buf, off, len);
			SwingUtilities.invokeLater(new Runnable() {
				public void run() {
					sb.append(message + "\n");
					text.setText(sb.toString());
				}
			});
		}
	}

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
		String gn = jTextField1.getText();
		String ucomment = jTextArea1.getText();

		CRUD.addcomment(gn,ucomment);
		JOptionPane.showMessageDialog(this, "评价成功");
		new MyorderUI().setVisible(true);
		this.dispose();
	}

	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
		new MyorderUI().setVisible(true);
		this.dispose();
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new UserCommentUI().setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTextArea jTextArea1;
	private javax.swing.JTextField jTextField1;
	// End of variables declaration//GEN-END:variables

}